<?php 
$language_array = array( 
/* Plugin Name of the plugin */
__( 'URL Shortify', 'url-shortify' ),
/* Plugin URI of the plugin */
__( 'http://wordpress.org/plugins/url-shortify', 'url-shortify' ),
/* Description of the plugin */
__( 'URL Shortify helps you beautify, manage, share & cloak any links on or off of your WordPress website. Create links that look how you want using your own domain name!', 'url-shortify' ),
/* Author of the plugin */
__( 'KaizenCoders', 'url-shortify' ),
/* Author URI of the plugin */
__( 'https://kaizencoders.com/', 'url-shortify' ),
__( 'Dashboard', 'url-shortify' ),
__( 'Links', 'url-shortify' ),
__( 'Groups', 'url-shortify' ),
__( 'Domains', 'url-shortify' ),
__( 'Tools', 'url-shortify' ),
__( '<span id="footer-thankyou">Thank you for creating with <a href="%1$s" target="_blank">WordPress</a> | URL Shortify <b>%2$s</b>. Developed by team <a href="%3$s" target="_blank">KaizenCoders</a></span>', 'url-shortify' ),
__( 'URL Shortify Quick Add', 'url-shortify' ),
__( 'General', 'url-shortify' ),
__( 'Redirection', 'url-shortify' ),
__( 'Nofollow', 'url-shortify' ),
__( 'Sponsored', 'url-shortify' ),
__( 'Parameter Forwarding', 'url-shortify' ),
__( 'Tracking', 'url-shortify' ),
__( 'Remove Data on Uninstall', 'url-shortify' ),
__( 'Check this box if you would like to remove all data when plugin is deleted.', 'url-shortify' ),
__( 'Settings', 'url-shortify' ),
__( 'Total Links', 'url-shortify' ),
__( 'Total Groups', 'url-shortify' ),
__( 'Total Clicks', 'url-shortify' ),
__( 'Unique Clicks', 'url-shortify' ),
__( 'Others', 'url-shortify' ),
__( 'Import', 'url-shortify' ),
__( 'Direct, Email, SMS', 'url-shortify' ),
__( 'Group', 'url-shortify' ),
__( 'You do not have permission to view statistics of this group.', 'url-shortify' ),
__( 'Name', 'url-shortify' ),
__( 'Clicks', 'url-shortify' ),
__( 'Created On', 'url-shortify' ),
__( '<a href="%s" class="text-indigo-600">Edit</a>', 'url-shortify' ),
__( '<a href="%s">Statistics</a>', 'url-shortify' ),
__( '<a href="%s">Delete</a>', 'url-shortify' ),
__( '<a href="%1$s"  title="%2$s" class="kc-us-group"/>%3$s</a>', 'url-shortify' ),
__( 'Delete', 'url-shortify' ),
__( 'You do not have permission to delete this group.', 'url-shortify' ),
__( 'Group has been deleted successfully!', 'url-shortify' ),
__( 'Groups(s) have been deleted successfully!', 'url-shortify' ),
__( 'Please select group(s) to delete.', 'url-shortify' ),
__( 'Group has been saved successfully!', 'url-shortify' ),
__( 'Edit Group', 'url-shortify' ),
__( 'Save Changes', 'url-shortify' ),
__( 'New Group', 'url-shortify' ),
__( 'Save Group', 'url-shortify' ),
__( 'You do not have permission to edit this group.', 'url-shortify' ),
__( 'Please Enter Name', 'url-shortify' ),
__( 'Search Groups', 'url-shortify' ),
__( 'Link', 'url-shortify' ),
__( 'Number of Links per page', 'url-shortify' ),
__( 'You do not have permission to view statistics of this link.', 'url-shortify' ),
__( 'Title', 'url-shortify' ),
__( 'Redirect Type', 'url-shortify' ),
__( 'Linked Post', 'url-shortify' ),
__( '<a href="%s" onclick="return confirmDelete();" >Delete</a>', 'url-shortify' ),
__( '<a href="%s" onclick="return confirmReset();" >Reset Stats</a>', 'url-shortify' ),
__( '<a href="%s" target="_blank" title="Visit Link"><i class="fa fa-external-link-square"></i></a>', 'url-shortify' ),
__( 'You do not have permission to delete this link.', 'url-shortify' ),
__( 'Link has been deleted successfully!', 'url-shortify' ),
__( 'You do not have permission to reset statistics of this link.', 'url-shortify' ),
__( 'Link stats has been reset successfully!', 'url-shortify' ),
__( 'Link(s) have been deleted successfully!', 'url-shortify' ),
__( 'Please select link(s) to delete.', 'url-shortify' ),
__( 'Link(s) stats have been reset successfully!', 'url-shortify' ),
__( 'Please select link(s) to reset stats.', 'url-shortify' ),
__( 'Link data have been saved successfully!', 'url-shortify' ),
__( 'Edit Link', 'url-shortify' ),
__( 'New Link', 'url-shortify' ),
__( 'Save Link', 'url-shortify' ),
__( 'You do not have permission to edit this form.', 'url-shortify' ),
__( 'Please enter Title', 'url-shortify' ),
__( 'Please enter Target URL', 'url-shortify' ),
__( 'Please enter valid Target URL', 'url-shortify' ),
__( 'Search Links', 'url-shortify' ),
__( 'IP', 'url-shortify' ),
__( 'URI', 'url-shortify' ),
__( 'Host', 'url-shortify' ),
__( 'Referrer', 'url-shortify' ),
__( 'Clicked On', 'url-shortify' ),
__( 'Info', 'url-shortify' ),
__( 'Your plugin plan is limited to 1 week of historical data. Upgrade your plan to see all historical data', 'url-shortify' ),
__( 'Upgrade Now', 'url-shortify' ),
__( 'Last Updated On: %s', 'url-shortify' ),
__( 'Refresh', 'url-shortify' ),
__( 'Create', 'url-shortify' ),
__( 'Clicks History', 'url-shortify' ),
__( '%d Total Clicks', 'url-shortify' ),
__( 'Top Locations', 'url-shortify' ),
__( '<a href="%s">Upgrade Now</a>', 'url-shortify' ),
__( 'Get insights about top locations from where people are clicking on your links.', 'url-shortify' ),
__( 'Referrers', 'url-shortify' ),
__( 'Know who are your top referrers.', 'url-shortify' ),
__( 'Top Devices', 'url-shortify' ),
__( 'Want to know which devices were used to access your links?', 'url-shortify' ),
__( 'Top Browsers', 'url-shortify' ),
__( 'Get information about browsers.', 'url-shortify' ),
__( 'Top Platforms', 'url-shortify' ),
__( 'Know more about which devices people used to access your links.', 'url-shortify' ),
__( 'Clicks Details', 'url-shortify' ),
__( 'Convert your long, ugly links into clean, memorable, shareable links', 'url-shortify' ),
__( 'Get Started', 'url-shortify' ),
__( 'Groups ', 'url-shortify' ),
__( 'Description', 'url-shortify' ),
__( 'Cancel', 'url-shortify' ),
__( 'Last 7 Days', 'url-shortify' ),
__( 'Last 30 Days', 'url-shortify' ),
__( 'Last 60 Days', 'url-shortify' ),
__( 'All Time', 'url-shortify' ),
__( 'Links Info', 'url-shortify' ),
__( 'Add New', 'url-shortify' ),
__( 'No Follow', 'url-shortify' ),
__( 'Links ', 'url-shortify' ),
__( 'Target URL', 'url-shortify' ),
__( 'Short URL', 'url-shortify' ),
__( 'Domain', 'url-shortify' ),
__( 'Select on which domain should this short link be accessible.', 'url-shortify' ),
__( 'Want to use shortlinks with custom domains? <a href="%s">Upgrade Now</a>', 'url-shortify' ),
__( 'No Group found. <a href="%s">Create a new Group</a> and add link to group.', 'url-shortify' ),
__( 'Expiration Date', 'url-shortify' ),
__( 'Set expiry date of the link with PRO version. <a href="%s">Upgrade Now</a>', 'url-shortify' ),
__( 'Password', 'url-shortify' ),
__( 'Protect your short link with password using PRO version. <a href="%s">Upgrade Now</a>', 'url-shortify' ),
__( 'Notes', 'url-shortify' ),
__( 'Import Short Links From <a href="%s" target="_blank">Pretty Links</a> WordPress Plugin', 'url-shortify' ),
__( 'Import Short Links From <a href="%s" target="_blank">URL Shortener by MyThemeShop</a> WordPress Plugin', 'url-shortify' ),
__( 'Import Short Links From <a href="%s" target="_blank">301 Redirect</a> WordPress Plugin', 'url-shortify' ),
__( 'Import Short Links From <a href="%s" target="_blank">Simple 301 Redirect</a> WordPress Plugin', 'url-shortify' ),
__( 'Import CSV File', 'url-shortify' ),
__( 'Import Short Links', 'url-shortify' ),
__( 'Show more details', 'url-shortify' ),
__( 'Short Link [URL Shortify]', 'url-shortify' ),
__( 'Short Link', 'url-shortify' ),
__( 'Short Link:', 'url-shortify' ),
__( 'Generate Short URL', 'url-shortify' ),
__( 'A Short URL will be created on Publish', 'url-shortify' ),
__( 'Just Now', 'url-shortify' ),
__( 'Copy', 'url-shortify' ),
__( 'Unique Clicks / Total Clicks', 'url-shortify' ),
__( 'Post', 'url-shortify' ),
__( 'Page', 'url-shortify' ),
__( 'WooCommerce', 'url-shortify' ),
__( 'Easy Digital Download', 'url-shortify' ),
__( 'Events Manager', 'url-shortify' ),
__( 'The Events Calendar', 'url-shortify' ),
__( 'Betterdocs', 'url-shortify' ),
__( 'WordPress Knowledgebase', 'url-shortify' ),
__( 'Modern Events', 'url-shortify' ),
__( 'No Data Found', 'url-shortify' ),
__( 'Count', 'url-shortify' ),
__( 'Cloak', 'url-shortify' ),
__( 'Meta Refresh', 'url-shortify' ),
__( 'Facebook', 'url-shortify' ),
__( 'Twitter', 'url-shortify' ),
__( 'Whatsapp', 'url-shortify' ),
__( 'Linkedin', 'url-shortify' ),
__( 'Pinterest', 'url-shortify' ),
__( 'Telegram', 'url-shortify' ),
__( 'VKontakte', 'url-shortify' ),
__( 'Email', 'url-shortify' ),
__( 'Hacker News', 'url-shortify' ),
__( 'QR Code', 'url-shortify' ),
__( 'SVG QR Code', 'url-shortify' ),
__( 'Share', 'url-shortify' ),
__( 'UTM Parameters', 'url-shortify' ),
__( 'Source', 'url-shortify' ),
__( 'Medium', 'url-shortify' ),
__( 'Campaign', 'url-shortify' ),
__( 'Term', 'url-shortify' ),
__( 'Content', 'url-shortify' ),
__( 'Reset', 'url-shortify' ),
__( 'Domain has been deleted successfully!', 'url-shortify' ),
__( 'Domain(s) have been deleted successfully!', 'url-shortify' ),
__( 'Please select domain(s) to delete.', 'url-shortify' ),
__( 'Domain has been saved successfully!', 'url-shortify' ),
__( 'Edit Domain', 'url-shortify' ),
__( 'New Domain', 'url-shortify' ),
__( 'Save Domain', 'url-shortify' ),
__( 'You do not have permission to edit this domain.', 'url-shortify' ),
__( 'Please Enter Host', 'url-shortify' ),
__( 'Search Domains', 'url-shortify' ),
__( 'Domains ', 'url-shortify' ),
__( 'SR', 'url-shortify' ),
__( 'Please enter valid password', 'url-shortify' ),
__( 'Reports', 'url-shortify' ),
__( 'Access Control', 'url-shortify' ),
__( 'Slug Character Count', 'url-shortify' ),
__( 'Public Link', 'url-shortify' ),
__( 'Enabling this option will give you the ability to turn your website into a link shortening service for your users. Once selected, you can display the link creation form with the <code>[url-shortify-form]</code> shortcode in any post or page on your website.', 'url-shortify' ),
__( 'Anonymise Clicks Data', 'url-shortify' ),
__( 'Anonymise all clicks data will anonymise all personal clicks data like IP address, User-Agents, Referrers, Country, OS, Device and more. You are still able to track clicks count', 'url-shortify' ),
__( 'Do Not Anonymise', 'url-shortify' ),
__( 'Anonymise All Clicks Data', 'url-shortify' ),
__( 'Anonymise Only IP Address', 'url-shortify' ),
__( 'Posts', 'url-shortify' ),
__( 'Pages', 'url-shortify' ),
__( 'Auto Create Links For', 'url-shortify' ),
__( 'Select Custom Post Type(s)', 'url-shortify' ),
__( 'Reporting Options', 'url-shortify' ),
__( 'Filter Robots', 'url-shortify' ),
__( 'Filter known Robots and unidentifiable browser clients from your click stats', 'url-shortify' ),
__( 'Excluded IP Addresses', 'url-shortify' ),
__( 'Enter IP Addresses or IP Ranges you want to exclude from your click stats. Each IP Address should be separated by commas. Example: 192.168.0.1, 192.168.2.1 or 192.168.*.*', 'url-shortify' ),
__( 'Access', 'url-shortify' ),
__( 'Create Link', 'url-shortify' ),
__( 'Manage Links', 'url-shortify' ),
__( 'Manage Groups', 'url-shortify' ),
__( 'Manage Custom Domains', 'url-shortify' ),
__( 'Popular Links', 'url-shortify' ),
__( 'Your browser does not support frames.', 'url-shortify' ),
__( 'The link you are trying to access is password protected.', 'url-shortify' ),
__( 'Enter', 'url-shortify' ),
/* translators: %s: PHP version */
__( 'URL Shortify requires PHP version %s+, plugin is currently NOT RUNNING.', 'url-shortify' ),
);
